version: '3.8'

services:
  whisper:
    build:
      context: .
      dockerfile: ./docker/whisper/Dockerfile
    container_name: video_translator_whisper
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - WHISPER_MODEL_SIZE=large-v3
      - WHISPER_BEAM_SIZE=5
      - WHISPER_TEMPERATURE=0.0
      - WHISPER_RESPONSE_FORMAT=json
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: video_translator_app
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./app:/app
    ports:
      - "8501:8501"
    depends_on:
      - whisper
    environment:
      - WHISPER_API_URL=http://whisper:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - DEFAULT_SOURCE_LANGUAGE=${DEFAULT_SOURCE_LANGUAGE:-ko}
      - SUPPORTED_LANGUAGES=${SUPPORTED_LANGUAGES:-en,ja,zh,de,id}
      - MAX_UPLOAD_SIZE_MB=${MAX_UPLOAD_SIZE_MB:-2000}
      - ALLOWED_VIDEO_FORMATS=${ALLOWED_VIDEO_FORMATS:-mp4,avi}
      - WHISPER_MODEL_SIZE=${WHISPER_MODEL_SIZE:-large-v3}
      - WHISPER_BEAM_SIZE=${WHISPER_BEAM_SIZE:-5}
      - WHISPER_TEMPERATURE=${WHISPER_TEMPERATURE:-0.0}
      - WHISPER_TIMESTAMP_GRANULARITY=${WHISPER_TIMESTAMP_GRANULARITY:-segment}
      - UPLOAD_DIR=${UPLOAD_DIR:-/data/uploads}
      - PROCESSED_DIR=${PROCESSED_DIR:-/data/processed}
      - RESULTS_DIR=${RESULTS_DIR:-/data/results}
      - DEBUG=${DEBUG:-false}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  data:
    driver: local

networks:
  video_translator_network:
    driver: bridge 